#!/bin/bash


python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "solve_opti_loss_size2"  --name 'opti_fc' --Pname 'opti_s1' --vanish 1 --seed 1 --wireless_seed 3
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "solve_opti_loss_size2"  --name 'opti_fc' --Pname 'opti_s2' --vanish 1 --seed 2 --wireless_seed 2
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "solve_opti_loss_size2"  --name 'opti_fc' --Pname 'opti_s3' --vanish 1 --seed 3 --wireless_seed 1
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'Sal_WR_fc' --Pname 'Sal_WR_s1' --seed 1 --wireless_seed 3
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'Sal_WR_fc' --Pname 'Sal_WR_s2' --seed 2 --wireless_seed 2
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'Sal_WR_fc' --Pname 'Sal_WR_s3' --seed 3 --wireless_seed 1
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'WR_fc' --Pname 'WR_s1' --seed 1 --wireless_seed 3 --aggregation 'oneK'
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'WR_fc' --Pname 'WR_s2' --seed 2 --wireless_seed 2 --aggregation 'oneK'
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'WR_fc' --Pname 'WR_s3' --seed 3 --wireless_seed 1 --aggregation 'oneK'
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_loss"  --name 'BL_fc' --Pname 'BL_s1' --seed 1 --wireless_seed 3
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_loss"  --name 'BL_fc' --Pname 'BL_s2' --seed 2 --wireless_seed 2
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_loss"  --name 'BL_fc' --Pname 'BL_s3' --seed 3 --wireless_seed 1
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "uni_random"  --name 'UR_fc' --Pname 'UR_s1' --seed 1 --wireless_seed 3
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "uni_random"  --name 'UR_fc' --Pname 'UR_s2' --seed 2 --wireless_seed 2
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "uni_random"  --name 'UR_fc' --Pname 'UR_s3' --seed 3 --wireless_seed 1
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_channel"  --name 'BC_fc' --Pname 'BC_s1' --seed 1 --wireless_seed 3
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_channel"  --name 'BC_fc' --Pname 'BC_s2' --seed 2 --wireless_seed 2
python main_fed.py --dataset synthetic0 --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_channel"  --name 'BC_fc' --Pname 'BC_s3' --seed 3 --wireless_seed 1


python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "solve_opti_loss_size2"  --name 'opti_fc' --Pname 'opti_s1' --vanish 1 --seed 1 --wireless_seed 3
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "solve_opti_loss_size2"  --name 'opti_fc' --Pname 'opti_s2' --vanish 1 --seed 2 --wireless_seed 2
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "solve_opti_loss_size2"  --name 'opti_fc' --Pname 'opti_s3' --vanish 1 --seed 3 --wireless_seed 1
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'Sal_WR_fc' --Pname 'Sal_WR_s1' --seed 1 --wireless_seed 3
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'Sal_WR_fc' --Pname 'Sal_WR_s2' --seed 2 --wireless_seed 2
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'Sal_WR_fc' --Pname 'Sal_WR_s3' --seed 3 --wireless_seed 1
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'WR_fc' --Pname 'WR_s1' --seed 1 --wireless_seed 3 --aggregation 'oneK'
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'WR_fc' --Pname 'WR_s2' --seed 2 --wireless_seed 2 --aggregation 'oneK'
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "weighted_random"  --name 'WR_fc' --Pname 'WR_s3' --seed 3 --wireless_seed 1 --aggregation 'oneK'
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_loss"  --name 'BL_fc' --Pname 'BL_s1' --seed 1 --wireless_seed 3
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_loss"  --name 'BL_fc' --Pname 'BL_s2' --seed 2 --wireless_seed 2
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_loss"  --name 'BL_fc' --Pname 'BL_s3' --seed 3 --wireless_seed 1
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "uni_random"  --name 'UR_fc' --Pname 'UR_s1' --seed 1 --wireless_seed 3
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "uni_random"  --name 'UR_fc' --Pname 'UR_s2' --seed 2 --wireless_seed 2
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "uni_random"  --name 'UR_fc' --Pname 'UR_s3' --seed 3 --wireless_seed 1
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_channel"  --name 'BC_fc' --Pname 'BC_s1' --seed 1 --wireless_seed 3
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_channel"  --name 'BC_fc' --Pname 'BC_s2' --seed 2 --wireless_seed 2
python main_fed.py --dataset syntheticiid --total_UE 30 --active_UE 10 --model synth_Net --round 200 --gpu -1 --optimizer fedprox --mu 1 --lr 0.1 --selection "best_channel"  --name 'BC_fc' --Pname 'BC_s3' --seed 3 --wireless_seed 1
